### ISSUE TITLE
WAL-G should support Google Cloud Storage

### ISSUE THREAD

**Issue by patrick-vbn** [wal-g/wal-g#11]
It would be wonderful if WAL-G would support storage to Google Cloud Storage.
For reference, Google Cloud Storage using Go is documented here: https://cloud.google.com/storage/docs/reference/libraries
https://godoc.org/cloud.google.com/go/storage

**Comment by GrappigPanda** [comment]
There's a related issue located here: https://github.com/wal-g/wal-g/issues/9

This is an interesting design point. Currently the `S3ReaderMaker` is explicitly aware that it uses S3 and references it here: https://github.com/wal-g/wal-g/blob/master/backup.go#L40

It seems, however, a better design might be that `ReaderMaker` is a struct whereas `Backup` could be the interface for different cloud storage providers. If `ReaderMaker` implementations are cloud-storage aware, `Backup` must also be aware. It may not be the best language to describe the problem, but `ReaderMaker` is-a generic cloud-storage aware interface which has-a specific cloud-storage structure `Backup`.

However, it seems that `ReaderMaker` could be a generic cloud-storage unaware structure which has-a cloud-storage aware interface of `Backup` (with implementations like `GcloudBackup`, `S3Backup`, &c.)

There's one thing which goes against-the-grain here and that's that `ReaderMaker` has a `Reader()` method. Currently the `S3ReaderMaker` is directly addressing `&s3.GetObjectInput()`, but it seems a `Backup` specific action--so, in essence, it seems that, instead of using `s3.GetObjectInput()`, it ought to `s.Backup.GetObject(path, key)`.

Regardless, it seems a better interface for enabling multi-cloud might be something along the lines of:
```go
type ReaderMaker struct {
	Backup     *Backup
	Key        *string
	FileFormat string
}

type Backup interface {
  ....
}

type S3Backup struct {
   ...
}

type GCloudBackup struct {
   ...
}
```

Input/harsh criticism welcome. This was mostly from a cursory glance in `backup.go`, so not too sure the repercussions of hte change at this stage.

**Comment by fdr** [comment]
The key considerations for accepting a patch that it has a good testing paradigm. In WAL-E I often had to make changes blind to backends that I did not develop. Sometimes, but not often, I could get expert help to maintain those, but it was quite rare over a long time scale.

So, while I'm not dismissing multiple backends out of hand, the software engineering bar is higher this time.

**Comment by fdr** [comment]
Well, I await a patch, unless someone wants to continue discussion.

**Comment by theckman** [comment]
@fdr why not leave it open with a `Help Wanted` tag?

**Comment by fdr** [comment]
I suppose because it clutters things -- not that I'm particularly super-tidy -- and the number of times I've seen that solicit work for a large feature is zero.

**Comment by GrappigPanda** [comment]
@fd Sorry I was expecting some sort of feedback toward the interface around which further storage provider options would be designed, but all I got was "write your tests" which ought to be standard practice in any modern project.

Did you have any input around the suggested interface? As stated earlier, perfectly willing to put in work to get this off the ground.

**Comment by theckman** [comment]
@GrappigPanda Depending on your work style, and my schedule, I may have some spare cycles to help out too, or at least provide some 👀  / testing of the resulting work.

Unrelated to the above, but I think you may have tagged the wrong user. /cc @fdr

**Comment by fdr** [comment]
I don't have strong opinions on how to organize the code: I think the devil in the details will be in getting as comprehensive coverage as feasible, including fault injection, with tests. To the extent I have stylistic issues, I will change things.

Also difficult will be maximuming that tests can have some consistency between backends: while platform-specific tests are not at all discouraged -- coverage is more important -- some thought should be paid to minimize drifting between backends by sharing code between tests.

Perhaps my programming epistemology is fatalistic, but I do not consider my ability to sight-read an interface as above and determine whether those goals are achieved, without putting in 10-20% of the time it would take to write the patch.

I will trust you as to how to achieve them, in which you should have a free hand. If I have stylistic complaints, with tests I can move things around. You might want to consider submitting a prototype and encountering some specific issues before gold-plating the engineering.

Does that help?

**Comment by GrappigPanda** [comment]
Nah, perfect response. I mostly wanted to avoid a drive-by commit with a
lot of different patches without having ran it by someone first.

**Comment by fdr** [comment]
I'll reopen the issue so it's easier to find unless everybody goes awol on me :)

**Comment by fdr** [comment]
I suppose it's a popular strain of software engineer that likes to micro-determine design details up-front (including myself, when I was younger). Sorry, I should have been more effusive in anticipation of that common expectation.

**Comment by x4m** [comment]
I'll close this in favor of #74 
We are moving in this direction...
