### ISSUE TITLE
Add Timeout and Retry for backup upload to S3

### ISSUE THREAD

**Issue by nikhil-postgres** [wal-g/wal-g#1166]
Hello Team,

### Database name
PostgreSQL 11.7

wal-g version v0.2.14 d372cbd 2019.12.04_06:14:06 PostgreSQL

# Issue description
Backup upload failing with 'Multipart Upload Error'

### Describe your problem
We have a few very large databases that are using wal-g for backup and restore. We are using S3 protocol for storing backups.These backups are failing with below error and we would like to add a "timeout" of 2 minutes so that it doesn't error out early

```
MultipartUpload: upload multipart failed
                                        upload id: 113688645168
                                caused by: RequestError: send request failed
                                caused by: Put https://<bucketname>/basebackups_005/base_0000000400003A2000000057/tar_partitions/part_146.tar.lz4?partNumber=4&uploadId=113688645168: read tcp ip-> ip: read: connection reset by peer
                                panic: packFileIntoTar: operation failed: PackFileTo: copy failed: io: read/write on closed pipe

                                goroutine 8350 [running]:
                                github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc000174460, 0xc0000379e0, 0x2b, 0x186cde0, 0xc000233c70, 0xc000174700, 0x0, 0x186c9c0, 0xc000384340)
                                        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:375 +0x10c
                                created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
                                        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:370 +0x5d0
```
 
We would also like to retry the backup if it does error out. Is there any inbuilt parameter that can be set for retry and timeout?

Thanks,
Nikhil

**Comment by nikhil-postgres** [comment]
Hello,

I see "WALG_S3_MAX_RETRIES" option is added in v1.1.2-rc . Is this a stable release and used in production databases? Not sure if it would be solve our problem but we can give it a try.

@usernamedt, Would be helpful if you could recommend something for this.

Thanks,
Nikhil

**Comment by usernamedt** [comment]
> Hello,
> 
> I see "WALG_S3_MAX_RETRIES" option is added in v1.1.2-rc . Is this a stable release and used in production databases? Not sure if it would be solve our problem but we can give it a try.
> 
> @usernamedt, Would be helpful if you could recommend something for this.
> 
> Thanks, Nikhil

Hi!

Actually, WAL-G v1.1 does not attempt to retry the `read: connection reset by peer` S3 storage adapter errors. However, WAL-G retries such errors since the [v1.1.1-rc](https://github.com/wal-g/wal-g/tree/v1.1.1-rc). Also, since the [v1.1.2-rc](https://github.com/wal-g/wal-g/releases/tag/v1.1.2-rc) there is an option called `WALG_S3_MAX_RETRIES` to configure the number of retries for the S3 API requests. So, from my POV, this should solve the mentioned `Multipart Upload Error`.

Both `v1.1.1-rc` and `v1.1.2-rc` are relatively new pre-releases intended to provide the above retries logic. Be aware that the backup sentinel format has been changed since the v1.1. Basically, it means that the delta backups feature is not forward-compatible, i.e. delta backups taken with the `v1.1.1-rc`+ versions can't be used with the v1.1, but delta backups taken with the `v1.1` can be used by the `v1.1.1-rc`+. That's why we plan to call the next release `v2.0.0`.

**Comment by nikhil-postgres** [comment]
Hi,

Thank you for the information. I think v1.1.2-rc is better suited for the requirement and v2.0.0 would be too. Any roadmap for release date for v2.0.0?

What does "-rc" mean at the end of v1.1.1 or v1.1.2?

**Comment by usernamedt** [comment]
> Hi,
> 
> Thank you for the information. I think v1.1.2-rc is better suited for the requirement and v2.0.0 would be too. Any roadmap for release date for v2.0.0?
> 
> What does "-rc" mean at the end of v1.1.1 or v1.1.2?

Hi! v2.0 is estimated to be released in Q4 2021/Q1 2022. As for "-rc", it stands for "release candidate".
