### ISSUE TITLE
New backups are deleted after upgrade

### ISSUE THREAD

**Issue by nikhil-postgres** [wal-g/wal-g#1288]
### Database name
PostgreSQL 

# Issue description
After an upgrade, if we take a new backup and run delete 7 days old backup, it will delete the new backup

### Describe your problem
We recently did an upgrade from 11.7 to 13.6. Our backup script will take a backup and delete backups older than 7 days. When we ran the script, we found that new backup is created for 13.6 but it gets deleted soon after.

This happens only if the timeline in storage is newer than the new cluster(13.6) timeline.

#####TimeLine check

[wal-verify] timeline check status: FAILURE
[wal-verify] timeline check details:
Highest timeline found in storage: 3
Current cluster timeline: 1

**Comment by x4m** [comment]
What version of WAL-G do you use? As far as I know we fixed this issue (unfortunately, at least twice).

**Comment by usernamedt** [comment]
This issue has been addressed in [this issue](https://github.com/wal-g/wal-g/issues/636). You can specify `--use-sentinel-time` flag to order backups by creation time during the backup deletion. However, there are some caveats. For example, suppose you have some garbage (for example, partially deleted backup) in the storage. In that case, it won't be deleted in this mode because WAL-G won't be able to distinguish it from the backup that is being created currently (in the case when delete command is being run concurrently with backup-push). This is why we did not make this behavior default. The recommended way is to switch to the new bucket after the upgrade.

**Comment by usernamedt** [comment]
I propose to continue the discussion [in this issue](https://github.com/wal-g/wal-g/issues/636) to avoid duplicates.
