### ISSUE TITLE
backup-push archive/tar: sockets not supported

### ISSUE THREAD

**Issue by dobrozhanskyi** [wal-g/wal-g#176]
env:
```
PGHOST=/data/patroni/
WALE_GS_PREFIX=gs://pg-backup/test
GOOGLE_APPLICATION_CREDENTIALS=/var/lib/postgresql/builder-pg-backup.json
```

```
postgres@patroni-3:/data/patroni$ /opt/wal-g backup-push /data/patroni
Path:  test/
INFO: 2019/01/30 13:43:52.789319 Doing full backup.
INFO: 2019/01/30 13:43:53.325025 Walking ...
INFO: 2019/01/30 13:43:53.325294 Starting part 1 ...
ERROR: 2019/01/30 13:43:53.326662 HandleWalkedFSObject: handle tar failed: handleTar: could not grab header info: archive/tar: sockets not supported
```

**Comment by dobrozhanskyi** [comment]
looks we need use tablespaces dir like `/data/patroni/global/`

**Comment by eraserx99** [comment]
Hi @dobrozhanskyi , I believe that you're using Patroni. The basic setup for Patroni places the UNIX SOCK file under the Postgres data directory. That's why you encountered the error above. If you configure that UNIX SOCK file out of the Psotgres data directory, you'll be fine. You can use the following configuration to instruct Patroni to do that,

```
  parameters:
    unix_socket_directories: "/var/run/postgresql"
```
 (I have /var/run/postgresql directory owned by postgres:postgres)
