### ISSUE TITLE
Backup from Standby Server

### ISSUE THREAD

**Issue by pinakesh** [wal-g/wal-g#338]
Hi Team,

Please can you let me know if it is possible to take backup from Standby Server and if it is possible then can you please provide the configuration steps to achieve this?

Regards,
Pinakesh

**Comment by x4m** [comment]
Hi @pinakesh !
If you are using PostgreSQL 9.6+ there is no difference between taking a backup from primary or standby.

**Comment by pinakesh** [comment]
Hi x4m,

Hope you are doing well.

Many thanks for responding, I tried backing up from standby just like primary and it is working fine.

Just needed to clear up a few more things?

1> In case we want to setup a transparent switchover/failover i.e. without any need to change configurations, would it be possible with wal-g?...I mean we can use the same config in both primary and standby but in that case same backups will be created on both the servers and hence there will be wastage of diskspace.

2> While backup is running, will wal-g be able to recover from errors and resume backup in case of errors like (lack of free space, power outage, system restart, system hangs, etc)?

3> While backup is running, is there any way to check the progress using :: 

i> Any Postgres table (similar to v$session_longops for RMAN in Oracle)
ii> Tools like Nagios/Icinga ??

4> Is backup-encryption possible with wal-g? If yes please can you provide the steps/link?

5> During backup process will wal-g prevent access to the database for readers or writers i.e. will there be any kind of locking on tables/tablespaces?

Regards,
Pinakesh

**Comment by x4m** [comment]
At Yandex our clusters each night are voting who of replicas will be doing backup. Preferred async replica with minimal lag. Otherwise, sync replica, if there is none - primary.
Backup on replica will fail in case of standby promotion or replication source promotion.
The backup will fail in case of long network outage, disk malfunction etc.
All garbage will be kept according to usual retention policy. I.e. if your backup failed at the very end and you delete retaining two weeks of backups - garbage will be kept for two weeks. Just in case.
3. No progress tracking is implemented now. But you can check log output - there will be information on how many tar files were archived. Each tar file represents roughly 1Gb.
4. Backups can be encrypted by OpenPGP, just give WAL-G a key.
5. Backup is totally seamless for DB users, except it consumes disk and network bandwidth. And, if not throttled and parallelized, WAL-G will eat one of these resources completely. You can throttle disk or network via settings.

**Comment by vivekrlokhande** [comment]
Hi
I have postgre1 and Postgre2 server running with Patroni. Initially Postgre2 is leader and we take basebackup and restore it on our standby server which gets successful. Later we do failover and use Postgre1 as leader. We take basebackup from now current leader and then restores it on standby sever. It fails  saying FATAL Error backup_label contains data inconsistent with control file. What could be the reason? or we doing something wrong?

**Comment by gitadf** [comment]
> At Yandex our clusters each night are voting who of replicas will be doing backup. Preferred async replica with minimal lag. Otherwise, sync replica, if there is none - primary.
...

Could you clarify how to set up voting which of the replicas will backup?
