### ISSUE TITLE
wal-g usage for backup repo server and cluster cloning

### ISSUE THREAD

**Issue by pinakesh** [wal-g/wal-g#346]
Hi Team,

I have below three queries on wal-g usage, kindly suggest.

1> Is using a centralized backup repository server possible with wal-g? i.e. taking backup (from standby server) using a remote server.

2> Is it possible to clone a cluster using backup files and archived wall files till the latest committed transaction? i.e. cloning a cluster using latest backup files and archived wals (created after the latest backup) 

3> Is it possible to validate backup pieces?

Regards,
Pinakesh

**Comment by x4m** [comment]
Hi!
1. No, WAL-G lives on the same machine as PostgreSQL. However, you can have a centralized storage system, but this will be a single point of failure.
2. Nope, the backup will be restored only to latest archived WAL segment (16Mb of logs). If you want "latest committed transaction" at the moment of opening copy for queries - you should use promotion of synchronous standby. Otherwise, you will not meet the requirements. But, I must note, in many scenarios they are pointless. Creating a copy from backup usually means "copy of the servers as it was a few seconds before", and this suffices.
3. We are working on backup validation. But this functionality is not implemented yet.
