### ISSUE TITLE
WAL-G for GCS: support customer-supplied encryption keys

### ISSUE THREAD

**Issue by NikolayS** [wal-g/wal-g#791]
To work with large files on GCS, support for Composite Objects was implemented https://cloud.google.com/storage/docs/composite-objects

It turns out that only Customer-managed encryption keys are incompatible with Composite Objects -- only Google-managed keys and Customer-supplied keys are
https://cloud.google.com/storage/docs/encryption/customer-supplied-keys

For better security, one might want to avoid working with Google-managed keys. Therefore, support for Customer-supplied keys is needed in WAL-G

Encryption key could be provided as variable. TODO:
- use the provided key to send it in headers (see `x-goog-encryption-key`, etc)
- prohibit working without HTTPS (is it possible?)

**Comment by NikolayS** [comment]
cc @agneum

**Comment by Wrhector** [comment]
@agneum @x4m This has a bad breaking change. The problem is in https://github.com/wal-g/storages/pull/36

The issues are in line https://github.com/wal-g/storages/blob/master/gcs/folder.go#L53 and https://github.com/wal-g/storages/blob/master/gcs/folder.go#L144

Even if no encryption key is supplied, the folder encryption key will be set so a byte array of 0s in `NewFolder`. The len check in `BuildObjectHandle`  will still return 32 so it means that if you don't provide a key, every file uploaded will have an encryption key of all zeros!

**Comment by agneum** [comment]
@Wrhector Thanks, you are right! I've prepared the PR to fix this issue: https://github.com/wal-g/storages/pull/37

@x4m please review
