### ISSUE TITLE
Remove dependency on external GPG

### ISSUE THREAD

**Issue by davidfetter** [wal-g/wal-g#92]
I'm [not the first person](https://github.com/wal-g/wal-g/pull/59) to have trouble on this score. It seems a lot cleaner just to cut the ties to `gpg` implementations and bundle the functionality with the binary.

**Comment by x4m** [comment]
OK, I think I should do that eventually.
Let's discuss some design decision.

Now WAL-G reflects the functionality of WAL-E: reads env var with key id and asks gpg for keys by id.

I can do:
1. Load keys from env var directly
2. Read gpg key store and extract keys myself

The first approach seems much cleaner. Second, preserves backward compatibility and get reed of gpg totally. First is easy to code with next to none place for bugs.

What do you think?

**Comment by davidfetter** [comment]
I think getting rid of gpg totally is a large part of the point of this exercise.

While keeping it easy to migrate from `wal-e` may be a nice-to-have, it's not something on which it's really worth spending a lot of engineering cycles at this stage of the project. There are already settings `wal-g` has that `wal-e` does not, and as the project matures, there will be more.

To see why having an external dependency on `gpg` is a bad idea, try running `wal-g` on an Ubuntu system using only Ubuntu tooling, i.e. using `pg_ctlcluster`, etc. Oh, and that `gpg` on such systems is not the latest--that's `gpg2`--is sooner rather than later going to be a security issue if it isn't already.

All this is a long-winded way of saying that we should concentrate on the following in the following order of priority:
 
1. Remove the `gpg` dependency while preserving the current usage
2. Figure out better ways to work with stores, as ease of use would dictate.

**Comment by dragonsmith** [comment]
@x4m Hey! Thanks for improving wal-g!

I think the idea to use a default gpg key store is a bit better overall than to store keys in env vars or files - you can manage them with a ready cli tool and use these keys for any other encryption processes. The problem is that the default gnupg package can be still too old (version 1....) and v2 key store is incompatible with v1. It raises the new choice: what key store version should wal-g use by default... Dunno what to suggest with it.

**Comment by x4m** [comment]
@dragonsmith thanks!
As far as I know, @Savichev-Igor was doing some work on organizing crypto around WAL-G. Though I do not know what's the current state of his research.

**Comment by davidfetter** [comment]
With utmost respect, the reason to ship `wal-g` with its own way to handle keys in the first place is that OSs frequently come with wrong versions of it. The `go` ecosystem is tuned up to avert problems of this type if we just work with it.

**Comment by Savichev-Igor** [comment]
Yes, i did a little research for this issue, but I couldn't find a good way for remove external GPG (anyway we need to keep backward compatibility in current version and can safely remove GPG in next major version)

At the moment i can try to implement:
- Mechanism that reads keys from ENV vars, as suggested by @x4m 
- Add a terrible warning about using an outdated version of GPG and recommend the user to specify keys in ENV vars, because soon we will remove external dependency from library

@davidfetter, @dragonsmith what do you think?

**Comment by x4m** [comment]
finally resolved #173
